# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-25 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0004_remove_book_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='img',
            field=models.ImageField(default=1, upload_to='', verbose_name='图片'),
            preserve_default=False,
        ),
    ]
