# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-25 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0006_remove_book_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='sale',
            field=models.IntegerField(default=1, verbose_name='已售'),
            preserve_default=False,
        ),
    ]
